# Generated by Django 3.2.7 on 2021-10-11 08:42

from django.db import migrations
import phonenumbers


def add_pure_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        phone = flat.owners_phonenumber
        parsed_phonenumber = phonenumbers.parse(phone, "RU")
        if phonenumbers.is_valid_number(parsed_phonenumber):
            pure_phonenumber = phonenumbers.format_number(parsed_phonenumber,
                                                          phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = pure_phonenumber
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_auto_20211011_0845'),
    ]

    operations = [
        migrations.RunPython(add_pure_phonenumber),
    ]
