# Generated by Django 2.2.20 on 2021-10-14 20:21

from django.db import migrations


def fill_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(owner=flat.owner,
                                    owner_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phonenumber=flat.owner_pure_phone,)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_auto_20211014_2051'),
    ]

    operations = [
        migrations.RunPython(fill_owner),
    ]
