# Generated by Django 2.2.20 on 2021-10-16 07:10

from django.db import migrations


def fill_flats_owners(apps, schema_editor):
    Owners = apps.get_model('property', 'Owner')
    Flats = apps.get_model('property', 'Flat')
    for owner in Owners.objects.all():
        flats = list(Flats.objects.filter(owner=owner.owner))
        owner.flat.set(flats, clear=True)


def move_backward(apps, schema_editor):
    Owners = apps.get_model('property', 'Owner')
    for owner in Owners.objects.all():
        owner.flat.set([], clear=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20211014_2221'),
    ]

    operations = [
        migrations.RunPython(fill_flats_owners, move_backward)
    ]
