# Generated by Django 3.2.7 on 2021-10-17 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0013_auto_20211016_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats_complained', to='property.flat', verbose_name='Квартира, на которую жаловались:'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(db_index=True, max_length=400, verbose_name='Текст жалобы:'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complained', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался:'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.TextField(db_index=True, help_text='ул. Подольских курсантов д.5 кв.4', verbose_name='Адрес квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.CharField(db_index=True, help_text='Первый этаж, последний этаж, пятый этаж', max_length=3, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(db_index=True, verbose_name='Новостройка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='town_district',
            field=models.CharField(blank=True, db_index=True, help_text='Чертаново Южное', max_length=50, verbose_name='Район города, где находится квартира'),
        ),
    ]
